{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "users",
    "label": "User",
    "query": "SELECT DISTINCT user_name\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND user_id IS NOT NULL"
   },
   {
    "name": "scopes",
    "label": "Scope",
    "query": "SELECT DISTINCT scope\nFROM events\nWHERE $__timeFilter(timestamp)"
   },
   {
    "name": "sources",
    "label": "Source",
    "query": "SELECT DISTINCT source\nFROM events\nWHERE $__timeFilter(timestamp)"
   },
   {
    "name": "projects",
    "label": "projects",
    "query": "SELECT DISTINCT project_id\nFROM events\nWHERE  $__timeFilter(timestamp)\n  AND project_id IS NOT NULL"
   },
   {
    "name": "tasks",
    "label": "Task",
    "query": "SELECT DISTINCT task_id\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND task_id IS NOT NULL"
   },
   {
    "name": "jobs",
    "label": "Job",
    "query": "SELECT DISTINCT job_id\nFROM events\nWHERE $__timeFilter(timestamp)\n  AND job_id IS NOT NULL"
   },
   {
    "name": "organizations",
    "label": "Organization",
    "query": "SELECT DISTINCT org_id\nFROM events\nWHERE $__timeFilter(timestamp)\nAND org_id IS NOT NULL"
   }
  ]
 },
 "panels": [
  {
   "title": "User Activity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(timestamp) as time, toString(user_name), count() as \" \"\r\nFROM events\r\nWHERE $__timeFilter(timestamp)\r\n  AND user_name IN (${users})\r\nGROUP BY time, user_name\r\nORDER BY time ASC, user_name ASC"
    }
   ]
  },
  {
   "title": "Working time & Activity by user",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  user_name as User,\r\n  sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as \"Working time(h)\",\r\n  count() as Activity,\r\n  countIf(scope IN ('draw:object')) as \"Activity(draw object)\",\r\n  countIf(scope NOT IN ('draw:object')) as \"Activity(else)\"\r\nFROM events\r\nWHERE JSONHas(payload, 'working_time')\r\n  AND $__timeFilter(timestamp)\r\n  AND user_name IN (${users})\r\n  AND (-1 IN (${projects}) OR project_id IN (${projects}))\r\n  AND (-1 IN (${tasks}) OR task_id IN (${tasks}))\r\n  AND (-1 IN (${jobs}) OR job_id IN (${jobs}))  \r\nGROUP BY user_id, user_name"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 11 },
   "targets": [
    {
     "rawSql": "# Detailed view Table\r\nSELECT\r\n  user_name as User,\r\n  project_id as Project,\r\n  task_id as Task,\r\n  job_id as Job, sum(JSONExtractUInt(payload, 'working_time')) / 1000 / 3600 as \"Working time(h)\",\r\n  count() as Activity\r\nFROM events\r\nWHERE JSONHas(payload, 'working_time')\r\n  AND $__timeFilter(timestamp)\r\n  AND user_name IN (${users})\r\n  AND (-1 IN (${projects}) OR project_id IN (${projects}))\r\n  AND (-1 IN (${tasks}) OR task_id IN (${tasks}))\r\n  AND (-1 IN (${jobs}) OR job_id IN (${jobs}))  \r\nGROUP BY user_id, user_name, project_id, task_id, job_id"
    }
   ]
  }
 ]
}